# YAML Schema for .documentory.yaml
$schema: "http://json-schema.org/draft-07/schema#"
title: "Documentory Config"
type: object
properties:
  documentation_paths:
    type: array
    items:
      type: string
    description: "Optional paths to folders with additional markdown files."
required: []
additionalProperties: false
